url: https://rabernat.github.io
baseurl:
plugins: ['jekyll/scholar']

# Site settings
title: Ryan Abernathey
email: rpa@ldeo.columbia.edu
description: "Big Data Oceanography"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 0099FF
  secondary: 00CCFF
  secondary-dark: 333

# pagination
paginate: 5
paginate_path: "/blog/page:num/"

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: envelope
    url: mailto:rpa@ldeo.columbia.edu
  - title: twitter
    url: http://twitter.com/rabernat
  - title: vimeo
    url: https://vimeo.com/user3588357
  - title: github
    url: http://github.com/rabernat
  - title: bitbucket
    url: http://bitbucket.org/ryanaberanthey

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty

# Bibliography settings
scholar:
  style: american-meteorological-society
  locale: en

  sort_by: year
  order: ascending

  source: ./_bibliography
  bibliography: references.bib
  bibliography_template: bib

  replace_strings: true
  join_strings:    true

  details_dir:    bibliography
  details_layout: bibtex.html
  details_link:   Details

  query: "@*"
